FROM node:22-alpine

WORKDIR /app

RUN npm install -g npm@10.8.2 && \
  npm install -g @nestjs/cli@10.0.0

COPY package*.json ./
RUN npm install

COPY . . 

RUN npm run build

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=10s --start-period=10s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1

CMD ["npm", "run", "start:dev"]